apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
spec:
  replicas: 1
  selector:
    matchLabels: { app: cart }
  template:
    metadata:
      labels: { app: cart }
    spec:
      containers:
        - name: cart
          image: <ACCOUNT_ID>.dkr.ecr.us-east-2.amazonaws.com/cart-service:latest
          ports: [{ containerPort: 3001 }]
          env:
            - name: DB_HOST
              valueFrom: { secretKeyRef: { name: rds-creds, key: DB_HOST } }
            - name: DB_PORT
              valueFrom: { secretKeyRef: { name: rds-creds, key: DB_PORT } }
            - name: DB_USER
              valueFrom: { secretKeyRef: { name: rds-creds, key: DB_USER } }
            - name: DB_PASS
              valueFrom: { secretKeyRef: { name: rds-creds, key: DB_PASS } }
            - name: DB_NAME
              valueFrom: { secretKeyRef: { name: rds-creds, key: DB_NAME } }
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  type: ClusterIP
  selector: { app: cart }
  ports: [{ port: 80, targetPort: 3001 }]
