apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: <ACCOUNT_ID>.dkr.ecr.us-east-2.amazonaws.com/payment-service:latest
          ports:
            - containerPort: 3004
          env:
            - name: DB_HOST
              valueFrom: { secretKeyRef: { name: rds-creds, key: DB_HOST } }
            - name: DB_PORT
              valueFrom: { secretKeyRef: { name: rds-creds, key: DB_PORT } }
            - name: DB_USER
              valueFrom: { secretKeyRef: { name: rds-creds, key: DB_USER } }
            - name: DB_PASS
              valueFrom: { secretKeyRef: { name: rds-creds, key: DB_PASS } }
            - name: DB_NAME
              valueFrom: { secretKeyRef: { name: rds-creds, key: DB_NAME } }
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  type: ClusterIP
  selector:
    app: payment
  ports:
    - port: 80
      targetPort: 3004
